# Generated by Django 4.2.16 on 2026-07-30 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_alter_organization_status'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='resource_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='resource_type',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='status',
            field=models.CharField(db_index=True, default='success', max_length=20),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['-timestamp'], name='core_activi_timesta_8baae3_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['organization', '-timestamp'], name='core_activi_organiz_2d34ab_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action', '-timestamp'], name='core_activi_action_1fc1d1_idx'),
        ),
    ]
