# Generated by Django 4.2.16 on 2026-07-26 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_department'),
        ('officers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='department',
        ),
        migrations.RemoveField(
            model_name='position',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
