# Generated by Django 4.2.16 on 2026-07-26 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0002_remove_officer_department_remove_position_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='level',
        ),
    ]
