# Generated by Django 4.2.16 on 2026-07-26 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0003_remove_position_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='position',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officer', to='officers.position'),
        ),
    ]
