# Generated by Django 4.2.16 on 2026-07-28 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('officers', '0004_position_one_to_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='organizations.organization'),
        ),
    ]
