# Generated by Django 4.2.16 on 2026-07-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0005_position_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='initials',
            field=models.CharField(blank=True, help_text='Default or custom initials for position', max_length=20),
        ),
    ]
