# Generated by Django 4.2.16 on 2026-08-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0006_position_initials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
