# Generated by Django 4.2.16 on 2026-07-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_marked_for_deletion_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('marked_for_deletion', 'Marked for Deletion')], db_index=True, default='pending', max_length=25),
        ),
    ]
