# Generated by Django 4.2.16 on 2026-08-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='theme',
            field=models.CharField(choices=[('pink', 'CSG Vibrant Pink'), ('blue', 'Ocean Blue'), ('emerald', 'Emerald Green'), ('purple', 'Royal Purple'), ('amber', 'Sunset Amber'), ('teal', 'Cyber Teal'), ('crimson', 'Crimson Rose'), ('dark', 'Midnight Slate')], default='pink', max_length=20),
        ),
    ]
