# Generated by Django 4.2.16 on 2026-08-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='theme',
            field=models.CharField(choices=[('pink', 'CSG Vibrant Pink'), ('blue', 'Ocean Blue'), ('emerald', 'Emerald Green'), ('purple', 'Royal Purple'), ('amber', 'Sunset Amber'), ('teal', 'Cyber Teal'), ('crimson', 'Crimson Rose'), ('dark', 'Midnight Slate'), ('indigo', 'Electric Indigo'), ('coral', 'Coral Sunset'), ('forest', 'Deep Forest'), ('nordic', 'Nordic Frost')], default='pink', max_length=20),
        ),
    ]
