# Generated by Django 4.2.16 on 2026-08-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organization_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='theme',
            field=models.CharField(choices=[('pink', 'CSG Vibrant Pink'), ('blue', 'Ocean Blue'), ('emerald', 'Emerald Green'), ('purple', 'Royal Purple'), ('amber', 'Sunset Amber'), ('teal', 'Cyber Teal'), ('crimson', 'Crimson Rose'), ('indigo', 'Electric Indigo'), ('coral', 'Coral Sunset'), ('forest', 'Deep Forest'), ('nordic', 'Nordic Frost'), ('sapphire', 'Sapphire Velvet'), ('amethyst', 'Amethyst Dusk'), ('rosegold', 'Rose Gold Lux'), ('monochrome', 'Slate Monochrome'), ('neon', 'Neon Cyber'), ('cherry', 'Sakura Cherry')], default='pink', max_length=20),
        ),
    ]
