# Generated by Django 4.2.16 on 2026-08-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='abbreviation',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
