# Generated by Django 4.2.16 on 2026-08-09 15:36

from django.db import migrations, models
import organizations.models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_organization_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=organizations.models.organization_logo_path),
        ),
    ]
