# Generated by Django 4.2.16 on 2026-08-15 00:53
# NOTE: abbreviation field was already added in migration 0009 via SeparateDatabaseAndState.
# This migration is kept as a no-op for compatibility with existing deployments.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_alter_organization_logo'),
    ]

    operations = [
        # No-op: abbreviation field already exists from migration 0009
    ]
