# Generated by Django 4.2.16 on 2026-08-09 15:36

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_dark_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_profile_picture_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_super_admin', 'Super Super Admin'), ('super_admin', 'Super Admin'), ('org_admin', 'Organization Admin'), ('president', 'President'), ('executive', 'Elected Officer'), ('committee_head', 'Committee Member')], default='committee_head', max_length=20),
        ),
    ]
