# Generated by Django 4.2.16 on 2026-08-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_profile_picture_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('org_admin', 'Organization Admin'), ('president', 'President'), ('executive', 'Elected Officer'), ('committee_head', 'Committee Member')], default='committee_head', max_length=20),
        ),
    ]
