# Generated by Django 4.2.16 on 2026-09-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('org_admin', 'Org Admin'), ('president', 'President'), ('executive', 'Elected Officer'), ('committee_head', 'Committee Member'), ('adviser', 'Adviser')], db_index=True, default='committee_head', max_length=20),
        ),
    ]
