# Generated by Django 4.2.16 on 2026-07-28 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('tasks', '0002_remove_task_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('processing', 'Processing'), ('to_advisers', 'To Advisers'), ('accounting', 'Accounting'), ('oca', 'OCA'), ('osas', 'OSAS'), ('ppss', 'PPSS'), ('supply', 'Supply'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='not_started', max_length=20),
        ),
    ]
