# Generated by Django 4.2.16 on 2026-07-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_organization_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('processing', 'Processing'), ('to_advisers', 'To Advisers'), ('accounting', 'Accounting'), ('oca', 'OCA'), ('osas', 'OSAS'), ('ppss', 'PPSS'), ('supply', 'Supply'), ('completed', 'Completed'), ('overdue', 'Overdue')], db_index=True, default='not_started', max_length=20),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['organization', 'status', 'is_archived'], name='tasks_task_organiz_41bef2_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['organization', 'due_date'], name='tasks_task_organiz_c58125_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'due_date'], name='tasks_task_status_0eabcf_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['-created_at'], name='tasks_task_created_5da2cb_idx'),
        ),
    ]
