# Generated by Django 4.2.16 on 2026-08-03

from django.db import migrations, models

def clean_overdue_task_statuses(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    # Move any overdue tasks back to active workflow status
    Task.objects.filter(status='overdue', progress__gt=0).update(status='processing')
    Task.objects.filter(status='overdue').update(status='not_started')

def reverse_clean(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_created_at_alter_task_due_date_and_more'),
    ]

    operations = [
        migrations.RunPython(clean_overdue_task_statuses, reverse_code=reverse_clean),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(
                choices=[
                    ('not_started', 'Not Started'),
                    ('processing', 'Processing'),
                    ('to_advisers', 'To Advisers'),
                    ('accounting', 'Accounting'),
                    ('oca', 'OCA'),
                    ('osas', 'OSAS'),
                    ('ppss', 'PPSS'),
                    ('supply', 'Supply'),
                    ('completed', 'Completed')
                ],
                db_index=True,
                default='not_started',
                max_length=20
            ),
        ),
    ]
