# Generated by Django 4.2.16 on 2026-08-10 07:47

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_clean_overdue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskattachment',
            name='file',
            field=models.FileField(storage=tasks.models.get_task_attachment_storage, upload_to='task_attachments/'),
        ),
    ]
