# Generated by Django 4.2.16 on 2026-08-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_taskattachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('document', 'Document'), ('multimedia', 'Multimedia'), ('other', 'Other')], db_index=True, default='document', max_length=20),
        ),
    ]
