# Generated by Django 4.2.16 on 2026-08-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('document', 'Document'), ('multimedia', 'Multimedia'), ('finance', 'Finance'), ('for_clarification', 'For Clarification'), ('event', 'Event'), ('other', 'Other')], default='document', max_length=30),
        ),
    ]
