# Generated by Django 4.2.16 on 2026-08-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_category'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['officer', 'task'], name='tasks_taska_officer_c8b529_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['task'], name='tasks_taska_task_id_8a87ae_idx'),
        ),
    ]
