# Generated by Django 4.2.16 on 2026-08-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_taskassignment_tasks_taska_officer_c8b529_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_task_organiz_41bef2_idx',
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['organization', 'is_archived', 'status'], name='tasks_task_organiz_9c5fd6_idx'),
        ),
    ]
