# Generated by Django 4.2.16 on 2026-09-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_fix_task_index_field_order'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_task_organiz_9c5fd6_idx',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('processing', 'Processing'), ('to_advisers', 'To Advisers'), ('accounting', 'Accounting'), ('oca', 'OCA'), ('osas', 'OSAS'), ('ppss', 'PPSS'), ('supply', 'Supply'), ('odi', 'ODI'), ('afms', 'AFMS'), ('completed', 'Completed')], db_index=True, default='not_started', max_length=20),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['organization', 'status', 'is_archived'], name='tasks_task_organiz_41bef2_idx'),
        ),
    ]
