# Generated by Django 4.2.16 on 2026-08-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_updated', 'Task Updated'), ('due_soon', 'Due Date Approaching'), ('overdue', 'Task Overdue'), ('task_completed', 'Task Completed'), ('approval_needed', 'Approval Needed'), ('comment_added', 'New Comment'), ('attachment_added', 'New Attachment'), ('system', 'System')], default='system', max_length=30),
        ),
    ]
